<a href="https://colab.research.google.com/github/tether007/Pytorch/blob/main/Pytorch01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##**Fundamentals of pytorch**
ref notebook="https://www.learnpytorch.io/00_pytorch_fundamentals/"

In [ ]:
import torch
import pandas as py
import matplotlib as mp
import numpy as np
print(torch.__version__)

2.5.0+cu121


In [ ]:
#scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
#getting tensor as int
scalar.item()

7

In [ ]:
#Vector
vector=torch.tensor([9,6])
vector

tensor([9, 6])

In [ ]:
torch.Size([2])

torch.Size([2])

In [ ]:
#Matrix
MATRIX=torch.tensor([[2,3],
                    [3,4]])
MATRIX
MATRIX.ndim

2

In [ ]:
MATRIX[0]

tensor([2, 3])

In [ ]:
MATRIX.shape

torch.Size([2, 2])

In [ ]:
#TENSOR
TENSOR = torch.tensor([[1,2,3],[4,3,5]])
TENSOR

tensor([[1, 2, 3],
        [4, 3, 5]])

In [ ]:
TENSOR.ndim

2

In [ ]:
TENSOR1=torch.tensor([[[1,3],[2,3]]])
TENSOR1.shape

torch.Size([1, 2, 2])

### **RANDOM TENSORS**
Random tensors are imp as NN(neural networs)genarally use these and keep on iterate the numbers to make a representation
TORCH random-->"https://pytorch.org/docs/stable/generated/torch.rand.html"

In [ ]:
random_tensor=torch.rand(3,4)
random_tensor


tensor([[0.9321, 0.6396, 0.2028, 0.5529],
        [0.4142, 0.7622, 0.3031, 0.4297],
        [0.6534, 0.3412, 0.6279, 0.5664]])

In [ ]:
#Create a random tensor similar shape to an image tensor
rand_image_size_tensor=torch.rand(size=(3,244,244))#size or doesnt matter on n the same
#here 3 is no:of color channels ie R G B and 244,244 are Height n bredth
rand_image_size_tensor

tensor([[[0.6101, 0.3508, 0.2129,  ..., 0.8545, 0.4759, 0.9839],
         [0.8634, 0.6974, 0.4627,  ..., 0.2300, 0.7674, 0.3086],
         [0.9434, 0.9403, 0.9153,  ..., 0.1110, 0.7011, 0.1443],
         ...,
         [0.4328, 0.2061, 0.8738,  ..., 0.6993, 0.8919, 0.9877],
         [0.9981, 0.0658, 0.7043,  ..., 0.3554, 0.0258, 0.0770],
         [0.1399, 0.6239, 0.1733,  ..., 0.8477, 0.5004, 0.9166]],

        [[0.5800, 0.1526, 0.2771,  ..., 0.3873, 0.4077, 0.4034],
         [0.2078, 0.6509, 0.1809,  ..., 0.2086, 0.4797, 0.2402],
         [0.0241, 0.5128, 0.8821,  ..., 0.8317, 0.7371, 0.0980],
         ...,
         [0.2927, 0.6578, 0.7346,  ..., 0.7307, 0.1490, 0.8090],
         [0.2406, 0.7043, 0.8040,  ..., 0.3150, 0.1727, 0.1194],
         [0.4584, 0.6018, 0.5142,  ..., 0.3104, 0.2013, 0.2132]],

        [[0.9411, 0.8859, 0.7598,  ..., 0.1180, 0.7353, 0.3602],
         [0.2368, 0.6046, 0.2193,  ..., 0.9973, 0.2239, 0.3697],
         [0.1867, 0.1934, 0.6595,  ..., 0.9821, 0.2220, 0.

### **ZEROS AND ONES**

In [ ]:
zeros=torch.zeros(size=(3,4))

In [ ]:
ones=torch.ones(size=(3,4))

In [ ]:
zeros*ones

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
ones.dtype#default type of tensors are float

torch.float32

### CREATING A RANGE OF TENSORS n TENSORS-LIKE

In [ ]:
one_to_10=torch.arange(0,10)
one_to_10
one_t0_1000=torch.arange(1,1000,19)#(start,end,step)
one_t0_1000

tensor([  1,  20,  39,  58,  77,  96, 115, 134, 153, 172, 191, 210, 229, 248,
        267, 286, 305, 324, 343, 362, 381, 400, 419, 438, 457, 476, 495, 514,
        533, 552, 571, 590, 609, 628, 647, 666, 685, 704, 723, 742, 761, 780,
        799, 818, 837, 856, 875, 894, 913, 932, 951, 970, 989])

In [ ]:
# creating tensors like
ten_zeros = torch.ones_like(one_to_10)
ten_zeros

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

### TENSOR DATATYPES
**NOTE**:Tensor datatypes is one of the 3 big errors
1. tensors not in right datatype
1. tensors not in right shape
1. tensors not on right device

In [ ]:
#float 32 tensor
f_32_tensor=torch.tensor([[[1,3,4],[2,3,4]]],dtype=None,#tensor's datatype
                         device=None,#what device is tensor on
                         requires_grad=False)#whether or not to track gradient

In [ ]:
f_32_tensor

tensor([[[1, 3, 4],
         [2, 3, 4]]])

In [ ]:
f_16_tensor=f_32_tensor.type(torch.half)
f_32_tensor*f_16_tensor

tensor([[[ 1.,  9., 16.],
         [ 4.,  9., 16.]]], dtype=torch.float16)

### GETTING INFO FROM TENSORS
1. tensors not in right datatype->tensor.dtype
2. tensors not in right shape->tensor.shape
3. tensors not on right device->tensor.device

In [ ]:
#create a tensor
sm_tensor = torch.rand(3,4)
sm_tensor

tensor([[0.9884, 0.1067, 0.4413, 0.7009],
        [0.6854, 0.8788, 0.2641, 0.7195],
        [0.4390, 0.6951, 0.8629, 0.5003]])

In [ ]:
print(sm_tensor.dtype)
print(sm_tensor.device)
print(sm_tensor.shape)

torch.float32
cpu
torch.Size([3, 4])


### Manipulating tensors

1. Addition
2. Sub
3. Multiplication
4. Division
5. Matrix Multiplication

In [ ]:
#tensor basic ops:
tensor = torch.tensor([1,2,3])
#tensor + 10
#tensor*10
#tensor-10


tensor([-9, -8, -7])

### Matrix multiplication
1. Element-wise and
2. Matrix wise(dot product)


In [ ]:
#Element wise mul
tensor = torch.tensor([68,34,120])
print(f'{tensor}*{tensor}={tensor*tensor}')

tensor([ 68,  34, 120])*tensor([ 68,  34, 120])=tensor([ 4624,  1156, 14400])


In [ ]:
#Matrix Multiplication
torch.matmul(tensor,tensor)

tensor(20180)

### one of the most common error in DL is shape error:
so to overcome issue of mat mul in pytorch:
1. we have to match the inner dimensions ie (MxN)(NxM)
2. The shape is of the outer dimension
(MxM)


In [ ]:
torch.matmul(torch.rand(5,6),torch.rand(6,6))

tensor([[1.7529, 1.2744, 1.0327, 1.5446, 1.8096, 1.3473],
        [2.2498, 1.3375, 1.4724, 1.9334, 2.2311, 1.5562],
        [1.7050, 0.7847, 1.2594, 1.3632, 1.5129, 1.0121],
        [2.1035, 1.4447, 1.0639, 1.8960, 2.1889, 1.8844],
        [2.0994, 1.0546, 1.5229, 1.7759, 1.7829, 1.2203]])

In [ ]:
# to deal with shape errors:Shapes for matrix multiplication
tensor1=torch.tensor([[1,2],
                      [2,3],
                      [4,5]])
tensor2=torch.tensor([[7,10],
                      [4,8],
                      [9,12]])



TO fix our shape issue we can transpose of the

In [ ]:
tensor2.T

tensor([[ 7,  4,  9],
        [10,  8, 12]])

In [ ]:
torch.mm(tensor1,tensor2.T)

tensor([[27, 20, 33],
        [44, 32, 54],
        [78, 56, 96]])

##Finding Min,max,mean,sum etc(tensor aggregation)

In [ ]:
x=torch.arange(1,100,12)
x

tensor([ 1, 13, 25, 37, 49, 61, 73, 85, 97])

In [ ]:
torch.max(x)#/x.max()

tensor(97)

In [ ]:
torch.mean(x,dtype=torch.float64)



tensor(49., dtype=torch.float64)

In [ ]:
x.sum()

tensor(441)

## Positional mean,min,max

In [ ]:
x=torch.arange(1,100,12)
x.argmin()#gives us the index of arg which is minimum value of a tensor


tensor(0)

In [ ]:
x.argmax()

tensor(8)

##reshaping,stacking,squeezing,unsqueezing
1. reshaping->reshapes an input tensor to a defined shape
2. View->returns a view of an input tensor while keeping the same memory as the original tensor
3. Stacking->combine multiple tensors on top of each other(vtack)or side by side (hstack)
4. squeeze->removes all '1' dimensions from a tensor
5. unsqueeze->add a 1 dimension to a tensor
6. permute->return a view of the input with dimensions permutted(swapped)in a certain way


In [ ]:
import torch
x=torch.arange(1.,10.)
x,x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [ ]:
#add extra dimension
x_reshaped=x.reshape(9,1)
x_reshaped

tensor([[1.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.],
        [9.]])

In [ ]:
x_reshaped.ndim

2

In [ ]:
#change the view(changes made to a view changes the actual tensor as it is connected to the main tensor)
z=x.view(9,1)
z


tensor([[1.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.],
        [9.]])

In [ ]:
y=torch.arange(0.,9.)
x_stacked=torch.stack([y,x,x],dim=0)
x_stacked

tensor([[0., 1., 2., 3., 4., 5., 6., 7., 8.],
        [1., 2., 3., 4., 5., 6., 7., 8., 9.],
        [1., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [ ]:
x_squeeze=torch.squeeze(x[8])
x


tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [ ]:
x

tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.])